// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdf4jymxvSpBcCzjMwBXLyOiLqIM8-7ZU',
    appId: '1:505261030730:android:c8169a4525604e65e0d5b3',
    messagingSenderId: '505261030730',
    projectId: 'poti-3c375',
    storageBucket: 'poti-3c375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVR4jpFTGpNYJYWQ5TdKZJ1PFEdtXzwrU',
    appId: '1:505261030730:ios:d1448b6cd63ebeb6e0d5b3',
    messagingSenderId: '505261030730',
    projectId: 'poti-3c375',
    storageBucket: 'poti-3c375.firebasestorage.app',
    iosBundleId: 'com.example.trabalhopoti',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmYtVGZwLidqUU-lrthH4JY_w5yqTG70E',
    appId: '1:505261030730:web:664fcd4810fd58c9e0d5b3',
    messagingSenderId: '505261030730',
    projectId: 'poti-3c375',
    authDomain: 'poti-3c375.firebaseapp.com',
    storageBucket: 'poti-3c375.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmYtVGZwLidqUU-lrthH4JY_w5yqTG70E',
    appId: '1:505261030730:web:e3eed855ca1870c8e0d5b3',
    messagingSenderId: '505261030730',
    projectId: 'poti-3c375',
    authDomain: 'poti-3c375.firebaseapp.com',
    storageBucket: 'poti-3c375.firebasestorage.app',
  );

}